# Generated by Django 5.2.17 on 2026-09-01 10:28

import apps.verification.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0004_alter_teacherassignment_options_and_more"),
        ("examinations", "0003_examcomponent"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResultVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verification_token",
                    models.CharField(
                        db_index=True,
                        default=apps.verification.models.generate_verification_token,
                        help_text="Cryptographically secure random verification token",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result_verifications",
                        to="examinations.exam",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result_verifications",
                        to="academics.studentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Result Verification",
                "verbose_name_plural": "Result Verifications",
                "ordering": ["-created_at", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "exam"),
                        name="unique_student_exam_verification",
                    )
                ],
            },
        ),
    ]
