# Generated by Django 5.2.17 on 2026-09-01 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0004_alter_teacherassignment_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Semester 5 End Semester Examination",
                        max_length=200,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exams",
                        to="academics.academicyear",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exams",
                        to="academics.semester",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam",
                "verbose_name_plural": "Exams",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["academic_year", "semester", "status"],
                        name="examination_academi_0995ca_idx",
                    ),
                    models.Index(
                        fields=["status"], name="examination_status_cc34a1_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "academic_year", "semester"),
                        name="unique_exam_name_per_academic_context",
                    )
                ],
            },
        ),
    ]
