# Generated by Django 5.2.17 on 2026-09-01 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_alter_teacherassignment_options_and_more"),
        ("examinations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "maximum_marks",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total maximum marks for this subject in this exam",
                        max_digits=6,
                    ),
                ),
                (
                    "passing_marks",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Minimum marks required to pass",
                        max_digits=6,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exam_subjects",
                        to="examinations.exam",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exam_subjects",
                        to="academics.subject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Subject",
                "verbose_name_plural": "Exam Subjects",
                "ordering": ["display_order", "id"],
                "indexes": [
                    models.Index(
                        fields=["exam", "is_active"],
                        name="examination_exam_id_5f69cc_idx",
                    ),
                    models.Index(
                        fields=["subject", "is_active"],
                        name="examination_subject_b61e37_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("exam", "subject"), name="unique_exam_subject_per_exam"
                    )
                ],
            },
        ),
    ]
