# Generated by Django 5.2.17 on 2026-09-01 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examinations", "0002_examsubject"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Internal, External, Practical", max_length=100
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Normalized uppercase identifier e.g. INTERNAL, EXTERNAL",
                        max_length=50,
                    ),
                ),
                (
                    "maximum_marks",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Maximum marks allocated to this component",
                        max_digits=6,
                    ),
                ),
                (
                    "passing_marks",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional passing marks requirement for this component",
                        max_digits=6,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exam_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="components",
                        to="examinations.examsubject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Component",
                "verbose_name_plural": "Exam Components",
                "ordering": ["display_order", "id"],
                "indexes": [
                    models.Index(
                        fields=["exam_subject", "is_active"],
                        name="examination_exam_su_eaed54_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("exam_subject", "code"),
                        name="unique_exam_subject_component_code",
                    )
                ],
            },
        ),
    ]
