# Generated by Django 5.2.17 on 2026-09-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("TEACHER", "Teacher"),
                    ("STUDENT", "Student"),
                ],
                default="STUDENT",
                help_text="Application role for access control",
                max_length=20,
            ),
        ),
    ]
