# Generated by Django 5.2.17 on 2026-09-01 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_academicyear_department_alter_classroom_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="semester",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subjects",
                to="academics.semester",
            ),
        ),
    ]
