# Generated by Django 5.2.17 on 2026-09-01 08:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_subject_semester"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teacherassignment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Teacher Assignment",
                "verbose_name_plural": "Teacher Assignments",
            },
        ),
        migrations.AlterUniqueTogether(
            name="teacherassignment",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="teacherassignment",
            name="academic_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="teacher_assignments",
                to="academics.academicyear",
            ),
        ),
        migrations.AddField(
            model_name="teacherassignment",
            name="assigned_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="teacherassignment",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="teacherassignment",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="teacher_assignments",
                to="academics.section",
            ),
        ),
        migrations.AddField(
            model_name="teacherassignment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="teacherassignment",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="teacher_assignments",
                to="academics.subject",
            ),
        ),
        migrations.AlterField(
            model_name="teacherassignment",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assignments",
                to="academics.teacherprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="teacherassignment",
            index=models.Index(
                fields=["teacher", "subject", "section", "academic_year", "is_active"],
                name="academics_t_teacher_e0e378_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="teacherassignment",
            index=models.Index(
                fields=["subject", "section", "academic_year", "is_active"],
                name="academics_t_subject_d35d5d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="teacherassignment",
            constraint=models.UniqueConstraint(
                fields=("teacher", "subject", "section", "academic_year"),
                name="unique_teacher_subject_section_academic_year",
            ),
        ),
        migrations.RemoveField(
            model_name="teacherassignment",
            name="classroom",
        ),
    ]
