# Generated by Django 5.2.17 on 2026-09-01 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0004_alter_teacherassignment_options_and_more"),
        ("examinations", "0003_examcomponent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarkEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "obtained_marks",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Marks obtained by the student for this component",
                        max_digits=6,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entered_by",
                    models.ForeignKey(
                        help_text="User (Teacher or Admin) who recorded these marks",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entered_marks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exam_component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mark_entries",
                        to="examinations.examcomponent",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mark_entries",
                        to="academics.studentprofile",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated these marks",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_marks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mark Entry",
                "verbose_name_plural": "Mark Entries",
                "ordering": ["-created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["student", "exam_component"],
                        name="marks_marke_student_d960f2_idx",
                    ),
                    models.Index(
                        fields=["exam_component", "is_active"],
                        name="marks_marke_exam_co_405847_idx",
                    ),
                    models.Index(
                        fields=["entered_by"], name="marks_marke_entered_659c44_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "exam_component"),
                        name="unique_student_exam_component_mark",
                    )
                ],
            },
        ),
    ]
