# Generated by Django 5.2.17 on 2026-09-01 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarkCorrectionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_marks",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Marks recorded at the time request was created",
                        max_digits=6,
                    ),
                ),
                (
                    "requested_marks",
                    models.DecimalField(
                        decimal_places=2, help_text="Newly proposed marks", max_digits=6
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Justification for the mark correction request"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("review_comment", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "mark_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="correction_requests",
                        to="marks.markentry",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requested_corrections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewed_corrections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mark Correction Request",
                "verbose_name_plural": "Mark Correction Requests",
                "ordering": ["-created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["mark_entry", "status"],
                        name="marks_markc_mark_en_a502ca_idx",
                    ),
                    models.Index(
                        fields=["requested_by", "status"],
                        name="marks_markc_request_2ce3b3_idx",
                    ),
                ],
            },
        ),
    ]
