import { useEffect, useState } from 'react'
import { FileText, Download, FilePlus2 } from 'lucide-react'
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Legend, LineChart, Line } from 'recharts'
import { getGeneratedReports, generateReport, getReportPreview, REPORT_TYPES } from '../../services/mock'
import PageHeader from '../../components/ui/PageHeader'
import Card from '../../components/ui/Card'
import Button from '../../components/ui/Button'
import Modal from '../../components/ui/Modal'
import Table from '../../components/ui/Table'
import StatusBadge from '../../components/ui/StatusBadge'
import Badge from '../../components/ui/Badge'
import EmptyState from '../../components/ui/EmptyState'
import { SkeletonBlock } from '../../components/ui/Skeleton'
import { useToast } from '../../context/ToastContext'
import { getCssVar, formatDate } from '../../utils/helpers'

function toCsv(rows) {
  if (!rows?.length) return ''
  const headers = Object.keys(rows[0])
  const lines = rows.map((r) => headers.map((h) => `"${(r[h] ?? '').toString().replace(/"/g, '""')}"`).join(','))
  return [headers.join(','), ...lines].join('\n')
}

function downloadCsv(filename, rows) {
  const blob = new Blob([toCsv(rows)], { type: 'text/csv;charset=utf-8;' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

export default function AdminReports() {
  const { toast } = useToast()
  const [loading, setLoading] = useState(true)
  const [reports, setReports] = useState([])
  const [previewType, setPreviewType] = useState(REPORT_TYPES[0])
  const [preview, setPreview] = useState([])
  const [previewLoading, setPreviewLoading] = useState(false)
  const [genOpen, setGenOpen] = useState(false)
  const [genType, setGenType] = useState(REPORT_TYPES[0])
  const [genRange, setGenRange] = useState('2025-2026')
  const [genBusy, setGenBusy] = useState(false)

  useEffect(() => {
    getGeneratedReports().then((res) => {
      setReports(res.data)
      setLoading(false)
    })
  }, [])

  useEffect(() => {
    setPreviewLoading(true)
    getReportPreview(previewType).then((res) => {
      setPreview(res.data)
      setPreviewLoading(false)
    })
  }, [previewType])

  const handleGenerate = async () => {
    setGenBusy(true)
    await generateReport(genType, genRange)
    setGenBusy(false)
    setGenOpen(false)
    toast.success('Report generated', 'A new report has been added to your library.')
    setLoading(true)
    getGeneratedReports().then((res) => {
      setReports(res.data)
      setLoading(false)
    })
  }

  const handleDownload = (report) => {
    if (!report.downloadable) {
      toast.info('Report is still generating', 'It will be available here shortly.')
      return
    }
    if (!preview?.length) {
      toast.info('Backend export pending', 'PDF/Excel exports are generated by the backend service.')
      return
    }
    downloadCsv(`examora-${report.name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}.csv`, preview)
    toast.success('Report downloaded', 'CSV exported successfully.')
  }

  const c = { primary: getCssVar('--primary', '#3157D5'), success: getCssVar('--success', '#16A34A'), accent: getCssVar('--accent', '#20B8D5'), muted: getCssVar('--muted', '#667085'), grid: getCssVar('--border', '#E6EAF0') }
  const tooltipStyle = { borderRadius: 10, border: `1px solid ${c.grid}`, background: getCssVar('--card', '#fff'), color: getCssVar('--text', '#172033') }

  const columns = [
    { key: 'name', header: 'Report', render: (r) => <span className="cell-main">{r.name}</span> },
    { key: 'period', header: 'Period', render: (r) => <span className="muted">{r.period}</span> },
    { key: 'generatedAt', header: 'Generated', render: (r) => <span className="muted">{formatDate(r.generatedAt)}</span> },
    { key: 'students', header: 'Students', render: (r) => <Badge variant="secondary">{r.students}</Badge> },
    { key: 'status', header: 'Status', render: (r) => <StatusBadge status={r.status} /> },
    { key: 'size', header: 'Size', render: (r) => <span className="muted">{r.size}</span> },
    {
      key: 'actions',
      header: '',
      style: { textAlign: 'right' },
      render: (row) => (
        <Button size="sm" variant="soft-primary" onClick={() => handleDownload(row)} disabled={row.status === 'GENERATING'}>
          <Download size={14} /> {row.status === 'GENERATING' ? <span className="spinner" style={{ width: 12, height: 12, borderWidth: 2 }} /> : 'Export'}
        </Button>
      ),
    },
  ]

  return (
    <div>
      <PageHeader
        title="Reports"
        subtitle="Generate, preview and export institution reports."
        actions={<Button onClick={() => setGenOpen(true)}><FilePlus2 size={16} /> Generate Report</Button>}
      />

      <div className="grid grid-2-main" style={{ marginBottom: 20 }}>
        <Card>
          <div className="card-header" style={{ flexWrap: 'wrap' }}>
            <h3>Report Library</h3>
            <div className="flex" style={{ gap: 6 }}>
              {REPORT_TYPES.map((t) => (
                <button key={t} className={`page-btn ${previewType === t ? 'active' : ''}`} onClick={() => setPreviewType(t)}>
                  {t[0].toUpperCase() + t.slice(1)}
                </button>
              ))}
            </div>
          </div>
          <div className="card-body">
            {loading ? (
              <SkeletonBlock rows={5} height={16} />
            ) : reports.length ? (
              <div className="flex flex-col" style={{ gap: 10 }}>
                {reports.slice(0, 5).map((r) => (
                  <div key={r.id} className="flex items-center justify-between" style={{ padding: '10px 0', borderBottom: '1px solid var(--border)' }}>
                    <div className="flex items-center" style={{ gap: 12 }}>
                      <span className="stat-icon ic-primary"><FileText size={18} /></span>
                      <div>
                        <div style={{ fontWeight: 600, fontSize: 13.5 }}>{r.name}</div>
                        <div className="muted" style={{ fontSize: 12 }}>{r.period} · {r.students} students</div>
                      </div>
                    </div>
                    <div className="flex items-center" style={{ gap: 10 }}>
                      <StatusBadge status={r.status} />
                      <button className="icon-btn" onClick={() => handleDownload(r)} aria-label="Download" disabled={r.status === 'GENERATING'}>
                        <Download size={16} />
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <EmptyState icon={FileText} title="No reports yet" description="Generate your first report to get started." />
            )}
          </div>
        </Card>

        <Card>
          <div className="card-header"><h3>Preview — {previewType[0].toUpperCase() + previewType.slice(1)}</h3></div>
          <div className="card-body">
            {previewLoading ? (
              <SkeletonBlock rows={6} height={18} />
            ) : preview?.length ? (
              <ResponsiveContainer width="100%" height={320}>
                {previewType === 'semester' ? (
                  <LineChart data={preview}>
                    <CartesianGrid strokeDasharray="3 3" stroke={c.grid} vertical={false} />
                    <XAxis dataKey="semester" tick={{ fill: c.muted, fontSize: 12 }} axisLine={false} tickLine={false} />
                    <YAxis domain={[0, 100]} tick={{ fill: c.muted, fontSize: 12 }} axisLine={false} tickLine={false} width={36} />
                    <Tooltip contentStyle={tooltipStyle} />
                    <Legend wrapperStyle={{ fontSize: 13 }} />
                    <Line type="monotone" dataKey="passRate" name="Pass %" stroke={c.primary} strokeWidth={3} dot={{ r: 4 }} />
                    <Line type="monotone" dataKey="avg" name="Avg" stroke={c.accent} strokeWidth={2} dot={{ r: 3 }} />
                  </LineChart>
                ) : (
                  <BarChart data={preview}>
                    <CartesianGrid strokeDasharray="3 3" stroke={c.grid} vertical={false} />
                    <XAxis dataKey={preview[0].dept ? 'dept' : preview[0].class ? 'class' : preview[0].name ? 'name' : 'class'} tick={{ fill: c.muted, fontSize: 12 }} axisLine={false} tickLine={false} />
                    <YAxis domain={[0, 100]} tick={{ fill: c.muted, fontSize: 12 }} axisLine={false} tickLine={false} width={36} />
                    <Tooltip contentStyle={tooltipStyle} />
                    <Legend wrapperStyle={{ fontSize: 13 }} />
                    <Bar dataKey="passRate" name="Pass Rate (%)" fill={c.success} radius={[6, 6, 0, 0]} maxBarSize={42} />
                    <Bar dataKey="avgMarks" name="Avg Marks" fill={c.primary} radius={[6, 6, 0, 0]} maxBarSize={42} />
                  </BarChart>
                )}
              </ResponsiveContainer>
            ) : (
              <EmptyState icon={FileText} title="No preview data" />
            )}
          </div>
        </Card>
      </div>

      <Card>
        <div className="card-header"><h3>All Generated Reports</h3></div>
        <div className="card-body">
          <Table columns={columns} data={reports} loading={false} empty={<EmptyState icon={FileText} title="No reports" />} />
        </div>
      </Card>

      <Modal open={genOpen} onClose={() => setGenOpen(false)} title="Generate Report" size="sm">
        <div className="form-group">
          <label className="form-label">Report type</label>
          <select className="form-control" value={genType} onChange={(e) => setGenType(e.target.value)}>
            {REPORT_TYPES.map((t) => <option key={t} value={t}>{t[0].toUpperCase() + t.slice(1)}</option>)}
          </select>
        </div>
        <div className="form-group">
          <label className="form-label">Period</label>
          <select className="form-control" value={genRange} onChange={(e) => setGenRange(e.target.value)}>
            <option value="2025-2026">2025-2026</option>
            <option value="2024-2025">2024-2025</option>
            <option value="All time">All time</option>
          </select>
        </div>
        <div className="flex" style={{ gap: 10, justifyContent: 'flex-end' }}>
          <Button variant="outline" onClick={() => setGenOpen(false)}>Cancel</Button>
          <Button onClick={handleGenerate} loading={genBusy}><FilePlus2 size={16} /> Generate</Button>
        </div>
      </Modal>
    </div>
  )
}